server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API and auth requests to monolith backend
    location /api/ {
        proxy_pass http://monolith-app:8088;
    }

    location /auth/ {
        proxy_pass http://monolith-app:8088;
    }
}
